# Generated by Django 4.2.16 on 2024-12-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newssletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewssLetter',
            new_name='NewsLetter',
        ),
    ]
