# Generated by Django 4.2.16 on 2024-12-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
