# Generated by Django 4.2.16 on 2024-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_login_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_require',
        ),
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
